/**
 * Pure initialization planning (S057).
 *
 * An initialization produces the minimal set of generated targets for a
 * supported application: the config file, the (empty) managed export region,
 * the aggregate stylesheet with the foundation tokens layer, explicit empty
 * themes/app stylesheets only when absent, the ordered layout imports, and the
 * initial lock. It never installs an unrequested component and never overwrites
 * existing application styles.
 *
 * The plan is data: no file is written and no writer is started.
 */
import path from "node:path";

import { ok, type ModelResult } from "../registry/errors.js";
import { deriveKitPaths, type KitConfig } from "../project/config.js";
import { INITIAL_TOOL_VERSION } from "../registry/versions.js";
import { composeManagedCss } from "./css.js";
import { patchExportRegion } from "./exports.js";
import type { KitLock } from "./lock.js";
import { observedText, type ProjectSnapshot } from "./snapshot.js";
import { patchLayoutImports } from "./svelte.js";

/** The frozen foundation layer declaration. */
export const TOKENS_BODY =
  "\n@layer svelte-ui-kit.tokens, svelte-ui-kit.themes, svelte-ui-kit.components;\n";

export interface PlannedWrite {
  readonly path: string;
  readonly bytes: Uint8Array;
}

export interface InitPlan {
  readonly writes: readonly PlannedWrite[];
  readonly lock: KitLock;
  readonly diagnostics: readonly string[];
}

export interface InitPlanInput {
  readonly config: KitConfig;
  readonly layoutFile: string;
  readonly layoutSource: string;
  readonly snapshot: ProjectSnapshot;
  readonly registryVersion: string;
  readonly registryHash: string;
  readonly configHash: string;
}

function textAt(snapshot: ProjectSnapshot, logicalPath: string): string | null {
  const observation = snapshot.entries.get(logicalPath);
  if (observation === undefined || observation.kind !== "file") return null;
  return observedText(observation);
}

function utf8(value: string): Uint8Array {
  return new TextEncoder().encode(value);
}

function relativeSpecifier(from: string, to: string): string {
  const relative = path.posix.relative(path.posix.dirname(from), to);
  return relative.startsWith(".") ? relative : `./${relative}`;
}

/**
 * Build the initialization plan. Only targets that are absent or that differ
 * from the generated bytes become writes; existing application styles are
 * preserved untouched.
 */
export function planInit(input: InitPlanInput): ModelResult<InitPlan> {
  const { config, snapshot } = input;
  const derived = deriveKitPaths(config);
  const writes: PlannedWrite[] = [];
  const diagnostics: string[] = [];

  const configJson = `${JSON.stringify(config, null, 2)}\n`;
  const existingConfig = textAt(snapshot, `${derived.stateDir}/kit.json`);
  if (existingConfig !== configJson) {
    writes.push({
      path: `${derived.stateDir}/kit.json`,
      bytes: utf8(configJson),
    });
  }

  const existingExports = textAt(snapshot, derived.rootExports) ?? "";
  const patchedExports = patchExportRegion(
    derived.rootExports,
    existingExports,
    [],
  );
  if (!patchedExports.ok) return patchedExports;
  if (patchedExports.value !== existingExports) {
    writes.push({
      path: derived.rootExports,
      bytes: utf8(patchedExports.value),
    });
  }

  const existingKitCss = textAt(snapshot, derived.kitCss) ?? "";
  const composed = composeManagedCss(existingKitCss, [
    { id: "tokens", body: TOKENS_BODY },
  ]);
  if (!composed.ok) return composed;
  if (composed.value !== existingKitCss) {
    writes.push({ path: derived.kitCss, bytes: utf8(composed.value) });
  }

  for (const [logicalPath, label] of [
    [derived.themesCss, "themes"],
    [derived.appCss, "app"],
  ] as const) {
    const existing = textAt(snapshot, logicalPath);
    if (existing === null) {
      diagnostics.push(
        `initialization reports absent empty ${label} stylesheet ${logicalPath}`,
      );
      writes.push({ path: logicalPath, bytes: new Uint8Array() });
    }
  }

  const importSpecifiers = [
    derived.kitCss,
    derived.themesCss,
    derived.appCss,
  ].map((target) => ({
    specifier: relativeSpecifier(input.layoutFile, target),
  }));
  const patchedLayout = patchLayoutImports(
    input.layoutSource,
    importSpecifiers,
  );
  if (!patchedLayout.ok) return patchedLayout;
  if (patchedLayout.value !== input.layoutSource) {
    writes.push({ path: input.layoutFile, bytes: utf8(patchedLayout.value) });
  }

  const lock: KitLock = {
    schemaVersion: 1,
    toolVersion: INITIAL_TOOL_VERSION,
    registryVersion: input.registryVersion,
    registryHash: input.registryHash,
    configHash: input.configHash,
    requested: [],
    items: [],
    files: [],
    cssBlocks: [],
    integrations: [
      {
        kind: "layout",
        path: input.layoutFile,
        baseline: "0".repeat(64),
        contract: "layout-v1",
      },
      {
        kind: "exports",
        path: derived.rootExports,
        baseline: "0".repeat(64),
        contract: "exports-v1",
      },
    ],
  };

  return ok({ writes, lock, diagnostics });
}
