/**
 * Pure initialization planning (S057).
 *
 * An initialization produces the minimal set of generated targets for a
 * supported application: the config file, the (empty) managed export region,
 * the aggregate stylesheet with the foundation tokens layer, explicit empty
 * themes/app stylesheets only when absent, the ordered layout imports, and the
 * initial lock. It never installs an unrequested component and never overwrites
 * existing application styles.
 *
 * Initialization consumes one complete project observation: every target it
 * reasons about must have been observed, and a target that is a symlink,
 * directory, FIFO or otherwise nonregular entry is a typed conflict rather
 * than an assumed absence. Text is decoded strictly (a byte-order mark is
 * preserved, an invalid sequence is refused). Managed markers alone never
 * confer ownership: an existing managed export region or CSS block is only
 * patchable when the observed lock already owns that integration, otherwise
 * the plan conflicts. The lock records real per-integration baselines and the
 * canonical config identity, and is schema-validated before it is returned.
 *
 * The plan is data: no file is written and no writer is started.
 */
import path from "node:path";

import { fail, issue, ok, type ModelResult } from "../registry/errors.js";
import {
  deriveKitPaths,
  parseKitConfig,
  type KitConfig,
} from "../project/config.js";
import { hashBytes } from "./compare.js";
import { composeManagedCss, FOUNDATION_TOKENS_CONTRACT } from "./css.js";
import { patchExportRegion, exportRegionContent } from "./exports.js";
import { parseManagedCss } from "./css-parse.js";
import { parseExportRegion } from "./export-parse.js";
import { parseKitLock, type KitLock, type LockIntegration } from "./lock.js";
import {
  decodeObservedText,
  type ProjectSnapshot,
  type TargetObservation,
} from "./snapshot.js";
import type { RegistrySnapshot } from "../registry/load.js";
import { INITIAL_TOOL_VERSION } from "../registry/versions.js";
import { patchLayoutImports, materializePassthroughLayout } from "./svelte.js";
import { resolveEffectiveConfig } from "./effective-config.js";

/** The frozen foundation layer declaration. */
export const TOKENS_BODY =
  "\n@layer svelte-ui-kit.tokens, svelte-ui-kit.themes, svelte-ui-kit.components;\n";

export type { ChangeOperation } from "./plan.js";
export type { PlanWrite as PlannedWrite } from "./plan.js";

import type { PlanWrite as PlannedWrite } from "./plan.js";

export interface InitPlan {
  readonly writes: readonly PlannedWrite[];
  readonly lock: KitLock;
  readonly diagnostics: readonly string[];
}

export interface InitPlanInput {
  readonly config: KitConfig;
  readonly layoutFile: string;
  readonly layoutSource: string;
  readonly snapshot: ProjectSnapshot;
  /** Validated registry snapshot; the authoritative registry identity. */
  readonly registry?: RegistrySnapshot;
  /** Deprecated scalar identity; ignored in favor of `registry`. */
  readonly registryVersion?: string;
  readonly registryHash?: string;
  readonly configHash: string;
}

function utf8(value: string): Uint8Array {
  return new TextEncoder().encode(value);
}

function relativeSpecifier(from: string, to: string): string {
  const relative = path.posix.relative(path.posix.dirname(from), to);
  return relative.startsWith(".") ? relative : `./${relative}`;
}

const SHA256 = /^[0-9a-f]{64}$/;

function unsafeTargetIssue(
  logicalPath: string,
  observation: TargetObservation,
): ModelResult<never> {
  const code =
    observation.kind === "unreadable"
      ? "INIT_TARGET_UNREADABLE"
      : "INIT_TARGET_UNSAFE";
  return fail([
    issue(
      code,
      `${logicalPath} is ${
        observation.kind === "unreadable"
          ? `unreadable (${observation.errorCode ?? "EIO"})`
          : `not a regular file (${observation.kind}); refusing to plan a write over it`
      }`,
      logicalPath,
    ),
  ]);
}

/**
 * Build the initialization plan. Only targets that are absent or that differ
 * from the generated bytes become writes; existing application styles are
 * preserved untouched.
 */
export function planInit(input: InitPlanInput): ModelResult<InitPlan> {
  const { snapshot } = input;
  if (input.registry === undefined) {
    return fail([
      issue(
        "INIT_REGISTRY_UNVERIFIED",
        "initialization requires a validated registry snapshot; a supplied scalar registry version/hash is not verifiable evidence",
        "registryHash",
      ),
    ]);
  }
  // One resolved effective mapping shared with add and sync: the captured
  // selected-project evidence and bounded `_kit/kit.json` discovery determine
  // the mapping before any target is planned, so an empty directory, a
  // malformed manifest, a non-SvelteKit package, an ambiguous manager or a
  // malformed/ambiguous discovery is a logical failure. A supplied stale
  // default never overrides an observed custom installation.
  const effective = resolveEffectiveConfig(snapshot, input.config);
  if (!effective.ok) return fail(effective.issues);
  if (effective.value.issues.length > 0) {
    const seen = new Set<string>();
    const issues = [];
    for (const entry of effective.value.issues) {
      if (seen.has(entry.code)) continue;
      seen.add(entry.code);
      issues.push(
        issue(
          "INIT_CONFIG_INVALID",
          `the effective kit configuration could not be proven (${entry.code}); reconcile the configuration before initialization`,
          entry.locator ?? "kit.json",
        ),
      );
    }
    return fail(issues);
  }
  const config: KitConfig = {
    ...effective.value.config,
    requested: [...effective.value.observedRequested],
  };
  const registryVersion = input.registry.root.registryVersion;
  const registryHash = input.registry.root.contentHash;

  const derived = deriveKitPaths(config);
  if (input.layoutFile !== config.layoutFile) {
    return fail([
      issue(
        "INIT_LAYOUT_MISMATCH",
        `the supplied layout ${JSON.stringify(input.layoutFile)} does not match the configured layout ${JSON.stringify(config.layoutFile)}`,
        input.layoutFile,
      ),
    ]);
  }
  const kitJsonPath = `${derived.stateDir}/kit.json`;
  const lockPath = `${derived.stateDir}/kit.lock.json`;
  const targets = {
    kitJson: kitJsonPath,
    lock: lockPath,
    rootExports: derived.rootExports,
    kitCss: derived.kitCss,
    themesCss: derived.themesCss,
    appCss: derived.appCss,
    layout: input.layoutFile,
  } as const;

  const observations = new Map<string, TargetObservation>();
  for (const logicalPath of new Set(Object.values(targets))) {
    const observation = snapshot.entries.get(logicalPath);
    if (observation === undefined) {
      return fail([
        issue(
          "INIT_OBSERVATION_INCOMPLETE",
          `${logicalPath} was not observed; initialization requires a complete project snapshot`,
          logicalPath,
        ),
      ]);
    }
    if (observation.kind !== "absent" && observation.kind !== "file") {
      return unsafeTargetIssue(logicalPath, observation);
    }
    observations.set(logicalPath, observation);
  }

  const textOf = (logicalPath: string): ModelResult<string | null> => {
    const observation = observations.get(logicalPath) as TargetObservation;
    if (observation.kind === "absent") return ok(null);
    const decoded = decodeObservedText(observation);
    if (decoded.kind === "invalid") {
      return fail([
        issue(
          "INIT_ENCODING_UNSUPPORTED",
          `${logicalPath} is not valid UTF-8; refusing to replace application bytes lossily`,
          logicalPath,
        ),
      ]);
    }
    return ok(decoded.kind === "text" ? decoded.text : null);
  };

  // Read the existing lock as ownership evidence.
  let existingLock: KitLock | null = null;
  const lockObservation = observations.get(lockPath) as TargetObservation;
  if (lockObservation.kind === "file") {
    const lockText = textOf(lockPath);
    if (!lockText.ok) return lockText;
    if (lockText.value !== null) {
      let parsedValue: unknown;
      try {
        parsedValue = JSON.parse(lockText.value);
      } catch {
        return fail([
          issue(
            "INIT_LOCK_INVALID",
            `${lockPath} is not valid JSON; reconcile the lock before initialization`,
            lockPath,
          ),
        ]);
      }
      const parsed = parseKitLock(parsedValue, lockPath, {
        stateDir: derived.stateDir,
        uiDir: config.uiDir,
        stylesDir: config.stylesDir,
        layoutFile: config.layoutFile,
      });
      if (!parsed.ok) return fail(parsed.issues);
      existingLock = parsed.value;
    }
  }

  const ownedIntegration = (
    kind: LockIntegration["kind"],
    logicalPath: string,
  ): boolean =>
    existingLock !== null &&
    existingLock.integrations.some(
      (integration) =>
        integration.kind === kind && integration.path === logicalPath,
    );

  // Existing managed regions are only patchable when the lock owns them.
  const exportsText = textOf(targets.rootExports);
  if (!exportsText.ok) return exportsText;
  let observedExportContent: string | null = null;
  if (exportsText.value !== null) {
    const parsedRegion = parseExportRegion(
      targets.rootExports,
      exportsText.value,
    );
    if (!parsedRegion.ok) return fail(parsedRegion.issues);
    if (parsedRegion.value.region !== null) {
      if (!ownedIntegration("exports", targets.rootExports)) {
        return fail([
          issue(
            "INIT_OWNERSHIP_CONFLICT",
            `${targets.rootExports} contains a managed export region that the lock does not own; markers alone do not confer ownership`,
            targets.rootExports,
          ),
        ]);
      }
      observedExportContent = exportsText.value.slice(
        parsedRegion.value.region.contentStart,
        parsedRegion.value.region.contentEnd,
      );
    }
  }

  const kitCssText = textOf(targets.kitCss);
  if (!kitCssText.ok) return kitCssText;
  if (kitCssText.value !== null) {
    const parsedCss = parseManagedCss(kitCssText.value);
    if (!parsedCss.ok) return fail(parsedCss.issues);
    if (
      parsedCss.value.blocks.length > 0 &&
      !ownedIntegration("stylesheet", targets.kitCss)
    ) {
      return fail([
        issue(
          "INIT_OWNERSHIP_CONFLICT",
          `${targets.kitCss} contains managed CSS blocks that the lock does not own; markers alone do not confer ownership`,
          targets.kitCss,
        ),
      ]);
    }
  }

  // Layout source and observation must agree when the file exists.
  const layoutObservation = observations.get(
    targets.layout,
  ) as TargetObservation;
  const layoutSource = input.layoutSource;
  if (layoutObservation.kind === "file") {
    const observed = textOf(targets.layout);
    if (!observed.ok) return observed;
    if (observed.value !== null && observed.value !== input.layoutSource) {
      return fail([
        issue(
          "INIT_LAYOUT_MISMATCH",
          `the observed ${targets.layout} differs from the supplied layout source; re-read the layout before planning`,
          targets.layout,
        ),
      ]);
    }
  }

  const writes: PlannedWrite[] = [];
  const diagnostics: string[] = [];

  const configJson = `${JSON.stringify(config, null, 2)}\n`;
  const configText = textOf(targets.kitJson);
  if (!configText.ok) return configText;
  // Malformed observed configuration must never be overwritten: reconcile it
  // explicitly rather than replacing application bytes lossily.
  if (configText.value !== null) {
    let parsedConfig: unknown;
    try {
      parsedConfig = JSON.parse(configText.value);
    } catch {
      return fail([
        issue(
          "INIT_CONFIG_INVALID",
          `${targets.kitJson} is not valid JSON; reconcile the configuration before initialization`,
          targets.kitJson,
        ),
      ]);
    }
    const validatedConfig = parseKitConfig(parsedConfig, targets.kitJson);
    if (!validatedConfig.ok) {
      const seen = new Set<string>();
      const issues = [];
      for (const entry of validatedConfig.issues) {
        if (seen.has(entry.code)) continue;
        seen.add(entry.code);
        issues.push(
          issue(
            "INIT_CONFIG_INVALID",
            `${targets.kitJson} is invalid (${entry.code}); reconcile the configuration before initialization`,
            targets.kitJson,
          ),
        );
      }
      return fail(issues);
    }
    // The observed file must still describe the resolved effective mapping; a
    // file that changed between discovery and observation is stale evidence
    // and must not be silently overwritten.
    const observedConfig = validatedConfig.value;
    if (
      observedConfig.registry !== config.registry ||
      observedConfig.uiDir !== config.uiDir ||
      observedConfig.stylesDir !== config.stylesDir ||
      observedConfig.layoutFile !== config.layoutFile
    ) {
      return fail([
        issue(
          "INIT_CONFIG_INVALID",
          `${targets.kitJson} no longer matches the resolved effective mapping; re-read the project configuration before initialization`,
          targets.kitJson,
        ),
      ]);
    }
  }
  if (configText.value !== configJson) {
    writes.push({
      path: targets.kitJson,
      operation: configText.value === null ? "create" : "update",
      bytes: utf8(configJson),
    });
  }

  const existingExports = exportsText.value ?? "";
  const existingExportsIntegration = existingLock?.integrations.find(
    (integration) =>
      integration.kind === "exports" &&
      integration.path === targets.rootExports,
  );
  let plannedExports: string;
  if (observedExportContent !== null) {
    // An owned, already-present region is preserved verbatim: initialization
    // never strips installed declarations. A region that no longer matches its
    // recorded baseline is customized application text and is refused rather
    // than reconciled lossily.
    if (
      existingExportsIntegration !== undefined &&
      (hashBytes(utf8(observedExportContent)) as string) !==
        existingExportsIntegration.baseline
    ) {
      return fail([
        issue(
          "INIT_OWNERSHIP_CONFLICT",
          `the owned ${targets.rootExports} export region differs from the recorded baseline; initialization will not overwrite customized bytes`,
          targets.rootExports,
        ),
      ]);
    }
    plannedExports = existingExports;
  } else {
    const patchedExports = patchExportRegion(
      targets.rootExports,
      existingExports,
      [],
    );
    if (!patchedExports.ok) return patchedExports;
    plannedExports = patchedExports.value;
    if (
      plannedExports !== existingExports &&
      ownedIntegration("exports", targets.rootExports)
    ) {
      return fail([
        issue(
          "INIT_OWNERSHIP_CONFLICT",
          `the owned ${targets.rootExports} export region differs from the recorded baseline; initialization will not overwrite customized bytes`,
          targets.rootExports,
        ),
      ]);
    }
    if (plannedExports !== existingExports) {
      writes.push({
        path: targets.rootExports,
        operation: exportsText.value === null ? "create" : "update",
        bytes: utf8(plannedExports),
      });
    }
  }

  const existingKitCss = kitCssText.value ?? "";
  // Preserve every managed block the lock already tracks by its observed body,
  // so initialization after an installation is a clean no-op rather than a
  // lossy rewrite. The foundation `tokens` layer is preserved when present (a
  // detached application-owned block stays byte-for-byte) and is created only
  // when the target has none.
  const parsedExistingKit = parseManagedCss(existingKitCss);
  if (!parsedExistingKit.ok) return parsedExistingKit;
  const existingKitBodies = new Map(
    parsedExistingKit.value.blocks.map((block) => [
      block.id,
      existingKitCss.slice(block.contentStart, block.contentEnd),
    ]),
  );
  // A recorded block is owned content that must exist. A block that the lock
  // tracks (registry `cssBlocks` or the `foundation-tokens-v1` integration) but
  // that is absent from the observed stylesheet is a conflict, never a silent
  // satisfied installation. A genuinely empty body is still present and stays
  // distinct from an absent block.
  const trackedKitBlockIds = new Set<string>();
  for (const record of existingLock?.cssBlocks ?? []) {
    if (record.path === targets.kitCss) trackedKitBlockIds.add(record.blockId);
  }
  const foundationTokensOwned =
    existingLock?.integrations.some(
      (integration) =>
        integration.kind === "stylesheet" &&
        integration.path === targets.kitCss &&
        integration.contract === FOUNDATION_TOKENS_CONTRACT,
    ) ?? false;
  if (foundationTokensOwned) trackedKitBlockIds.add("tokens");
  for (const blockId of [...trackedKitBlockIds].sort()) {
    if (!existingKitBodies.has(blockId)) {
      return fail([
        issue(
          "INIT_OWNERSHIP_CONFLICT",
          `${targets.kitCss} records the ${JSON.stringify(blockId)} block as owned but the observed block is absent; tracked missing content must be reconciled explicitly rather than reported as satisfied`,
          targets.kitCss,
        ),
      ]);
    }
  }
  const desiredKitBlocks: { id: string; body: string }[] = [
    ...(existingLock?.cssBlocks ?? [])
      .filter((record) => record.path === targets.kitCss)
      .map((record) => ({
        id: record.blockId,
        body: existingKitBodies.get(record.blockId) as string,
      })),
  ];
  if (!desiredKitBlocks.some((block) => block.id === "tokens")) {
    desiredKitBlocks.unshift({
      id: "tokens",
      body: existingKitBodies.get("tokens") ?? TOKENS_BODY,
    });
  }
  const composed = composeManagedCss(existingKitCss, desiredKitBlocks);
  if (!composed.ok) return composed;
  const plannedKitCss = composed.value;
  if (
    plannedKitCss !== existingKitCss &&
    ownedIntegration("stylesheet", targets.kitCss)
  ) {
    return fail([
      issue(
        "INIT_OWNERSHIP_CONFLICT",
        `the owned ${targets.kitCss} managed stylesheet differs from the recorded baseline; initialization will not overwrite customized bytes`,
        targets.kitCss,
      ),
    ]);
  }
  if (plannedKitCss !== existingKitCss) {
    writes.push({
      path: targets.kitCss,
      operation: kitCssText.value === null ? "create" : "update",
      bytes: utf8(plannedKitCss),
    });
  }

  for (const [logicalPath, label] of [
    [targets.themesCss, "themes"],
    [targets.appCss, "app"],
  ] as const) {
    const observation = observations.get(logicalPath) as TargetObservation;
    if (observation.kind === "absent") {
      diagnostics.push(
        `initialization reports absent empty ${label} stylesheet ${logicalPath}`,
      );
      writes.push({
        path: logicalPath,
        operation: "create",
        bytes: new Uint8Array(),
      });
    }
  }

  const importSpecifiers = [
    derived.kitCss,
    derived.themesCss,
    derived.appCss,
  ].map((target) => ({
    specifier: relativeSpecifier(input.layoutFile, target),
  }));
  // An absent layout has no implicit child rendering to preserve, so it is
  // materialized as a minimal Svelte 5 passthrough layout. An existing layout
  // receives only the missing imports and keeps its exact rendering/snippet
  // behavior; rendering is never appended to an intentionally blank/custom
  // layout by guess.
  let layoutText: string;
  if (layoutObservation.kind === "absent") {
    layoutText = materializePassthroughLayout(importSpecifiers);
  } else {
    const patchedLayout = patchLayoutImports(layoutSource, importSpecifiers);
    if (!patchedLayout.ok) return patchedLayout;
    layoutText = patchedLayout.value;
  }
  // An absent layout must still be created even when the supplied source
  // already contains the imports; otherwise a baseline would be claimed for a
  // file that does not exist. Only when the layout is an existing, unchanged
  // file are the bytes left alone.
  const layoutUnchanged =
    layoutObservation.kind === "file" && layoutText === layoutSource;
  if (!layoutUnchanged) {
    writes.push({
      path: input.layoutFile,
      operation: layoutObservation.kind === "absent" ? "create" : "update",
      bytes: utf8(layoutText),
    });
  }

  const configHash = hashBytes(utf8(configJson)) as string;
  if (!SHA256.test(registryHash)) {
    return fail([
      issue(
        "INIT_REGISTRY_HASH_INVALID",
        "the registry identity is not a 64-character lowercase hex digest",
        "registryHash",
      ),
    ]);
  }

  // Preserve the recorded integration lineage. Initialization must never
  // convert aggregate `stylesheet-v1` bookkeeping into `foundation-tokens-v1`
  // ownership merely because the retained text happens to equal TOKENS_BODY:
  // markers, aggregate presence and byte equality cannot reclaim a detached
  // application-owned block. A fresh initialization establishes the foundation
  // contract; an existing installation keeps its explicit contract and
  // legitimate baseline.
  const priorIntegration = (
    kind: LockIntegration["kind"],
    logicalPath: string,
  ): LockIntegration | undefined =>
    existingLock?.integrations.find(
      (entry) => entry.kind === kind && entry.path === logicalPath,
    );
  const priorLayout = priorIntegration("layout", input.layoutFile);
  const priorStylesheet = priorIntegration("stylesheet", targets.kitCss);
  const priorExports = priorIntegration("exports", targets.rootExports);
  const exportsChanged = plannedExports !== existingExports;
  const layoutHash = hashBytes(utf8(layoutText)) as string;
  const exportsRegionHash = hashBytes(
    utf8(exportRegionContent(targets.rootExports, plannedExports) ?? ""),
  ) as string;

  const integrations: LockIntegration[] = (
    [
      {
        kind: "layout",
        path: input.layoutFile,
        baseline: layoutUnchanged
          ? (priorLayout?.baseline ?? layoutHash)
          : layoutHash,
        contract: priorLayout?.contract ?? "layout-v1",
      },
      {
        kind: "stylesheet",
        path: targets.kitCss,
        baseline:
          priorStylesheet?.baseline ?? (hashBytes(utf8(TOKENS_BODY)) as string),
        contract: priorStylesheet?.contract ?? FOUNDATION_TOKENS_CONTRACT,
      },
      {
        kind: "exports",
        path: targets.rootExports,
        baseline: exportsChanged
          ? exportsRegionHash
          : (priorExports?.baseline ?? exportsRegionHash),
        contract: priorExports?.contract ?? "exports-v1",
      },
    ] satisfies LockIntegration[]
  ).sort((left, right) => {
    if (left.path !== right.path) return left.path < right.path ? -1 : 1;
    if (left.kind === right.kind) return 0;
    return left.kind < right.kind ? -1 : 1;
  });

  const lock: KitLock = {
    schemaVersion: 1,
    toolVersion: INITIAL_TOOL_VERSION,
    registryVersion,
    registryHash,
    configHash,
    // Preserve the recorded lineage. Initialization establishes the baseline;
    // it must never reset an installed/customized lock to empty.
    requested: existingLock?.requested ?? [],
    items: existingLock?.items ?? [],
    files: existingLock?.files ?? [],
    cssBlocks: existingLock?.cssBlocks ?? [],
    integrations,
  };

  const validated = parseKitLock(lock, lockPath, {
    stateDir: derived.stateDir,
    uiDir: config.uiDir,
    stylesDir: config.stylesDir,
    layoutFile: config.layoutFile,
  });
  if (!validated.ok) return fail(validated.issues);
  const finalLock = validated.value;

  // Lock metadata is part of the explicit plan: write the deterministic lock
  // unless the effective lock is already exactly the recorded one (a satisfied
  // replay is a no_change).
  const lockChanged =
    existingLock === null ||
    JSON.stringify(existingLock) !== JSON.stringify(finalLock);
  if (lockChanged) {
    writes.push({
      path: lockPath,
      operation: existingLock === null ? "create" : "update",
      bytes: utf8(`${JSON.stringify(finalLock, null, 2)}\n`),
    });
  }

  return ok({ writes, lock: finalLock, diagnostics });
}
